### ISSUE TITLE
Add user documentation

### ISSUE THREAD

**Issue by bugwelle** [Komet/MediaElch#531]
I'll add some basic end-user documentation. This is a discussion thread for it.

## Tools
[Sphinx](http://www.sphinx-doc.org/en/master/) is an awesome tool for documentation generation. Documentation is written using [reStructuredText](http://docutils.sourceforge.net/rst.html) and can be compiled to HTML, LaTeX and more.

### Theme
Sphinx has a lot themes. I like https://sphinx-rtd-theme.readthedocs.io/en/latest/ a lot :-)

## Repository
I suggest adding a new repository for documentation. Otherwise we'll just bloat this one up by updating screenshots, etc.

The MediaElch organization already exists on GitHub: https://github.com/mediaelch  
What should be the repository's name?

 -  https://github.com/mediaelch/documentation
 -  https://github.com/mediaelch/doc
 -  https://github.com/mediaelch/mediaelch-doc

We can then host the documentation using GitHub Pages.

## Documentation Structure

I propose:

```
  - About 
  - Release Notes 
  - Contributing 
    - Build MediaElch
    - Issues
    - Translations
  - Settings
    - Advanced Settings
  - Installation
  - Quick Start Guide
  - Troubleshooting
  - FAQ
  - Movie
  - Tv Shows
  - Concert
  - Music
  - Export
  - Renamer
  - Synchronization with Kodi
```

## Todo

- [x] plan documentation structure (see above)
- [x] create a new repository
- [x] add first documentation draft
- [x] add screenshots

**Comment by bugwelle** [comment]
I've set up a temporary repository to test and add documentation:

https://github.com/bugwelle/mediaelch-doc

**Comment by bugwelle** [comment]
Transferred ownership of my repository. It is now available at:

 - https://github.com/mediaelch/mediaelch-doc/
 - https://mediaelch.github.io/mediaelch-doc/

When the documentation is mostly done then I'll add it as a git submodule to this repository.

**Comment by bugwelle** [comment]
Documentation is now included as  a git submodule.
