### ISSUE TITLE
[Roadmap] Internal Changes

### ISSUE THREAD

**Issue by bugwelle** [Komet/MediaElch#656]
Just a list of todos for internal changes

- [x]  use `#pragma once` instead of include guards
- [x] remove all uses of old enums (use scoped enums instead)
   - [x]  `FileScannerDialog.h` => `ReloadType`
- [x]  restructure folders into UI and non-UI parts
- [x] remove usage of `QSettings` and replace with mockable class
- [x] Move static "Helper" methods into free functions
- [x]  Move from `QList<T>` to `QVector<T>` as default
- [x]  split settings class into smaller ones
- [x] Remove all `foreach` macros (#664)
- [x] Remove "magic" string literals for scrapers (#674)
- [x] Refactor TvShowModel
